package lasalle.edu.co.views.relacionamientoestratégico;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H6;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import com.vaadin.flow.theme.lumo.LumoUtility.Padding;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Relacionamiento Estratégico")
@Route("my-view9")
@Menu(order = 2, icon = LineAwesomeIconUrl.PENCIL_RULER_SOLID)
public class RelacionamientoEstratégicoView extends Composite<VerticalLayout> {

        public RelacionamientoEstratégicoView() {
                VerticalLayout layoutColumn2 = new VerticalLayout();
                HorizontalLayout layoutRow7 = new HorizontalLayout();
                HorizontalLayout layoutRow = new HorizontalLayout();
                HorizontalLayout layoutRow2 = new HorizontalLayout();
                VerticalLayout layoutColumn4 = new VerticalLayout();
                Icon icon = new Icon();
                VerticalLayout layoutColumn5 = new VerticalLayout();
                H1 h1 = new H1();
                VerticalLayout layoutColumn6 = new VerticalLayout();
                HorizontalLayout layoutRow3 = new HorizontalLayout();
                VerticalLayout layoutColumn7 = new VerticalLayout();
                VerticalLayout layoutColumn3 = new VerticalLayout();
                HorizontalLayout layoutRow4 = new HorizontalLayout();
                Button buttonSecondary = new Button();
                Paragraph textMedium = new Paragraph();
                Paragraph textMedium2 = new Paragraph();
                VerticalLayout layoutColumn8 = new VerticalLayout();
                HorizontalLayout layoutRow5 = new HorizontalLayout();
                VerticalLayout layoutColumn9 = new VerticalLayout();
                HorizontalLayout layoutRow8 = new HorizontalLayout();
                VerticalLayout layoutColumn10 = new VerticalLayout();
                HorizontalLayout layoutRow6 = new HorizontalLayout();
                VerticalLayout layoutColumn11 = new VerticalLayout();
                H6 h6 = new H6();
                VerticalLayout layoutColumn12 = new VerticalLayout();
                HorizontalLayout layoutRow9 = new HorizontalLayout();
                getContent().setHeightFull();
                getContent().setWidthFull();
                layoutColumn2.getStyle().set("width", "100%");
                layoutColumn2.getStyle().set("flex-grow", "1");
                layoutRow7.addClassName(Gap.MEDIUM);
                layoutRow7.getStyle().set("width", "100%");
                layoutRow7.getStyle().set("height", "min-content");
                layoutRow.addClassName(Gap.MEDIUM);
                layoutRow.getStyle().set("width", "100%");
                layoutRow.getStyle().set("height", "min-content");
                layoutRow.setAlignItems(Alignment.CENTER);
                layoutRow.setJustifyContentMode(JustifyContentMode.CENTER);
                layoutRow2.addClassName(Gap.MEDIUM);
                layoutRow2.getStyle().set("width", "100%");
                layoutRow2.getStyle().set("height", "min-content");
                layoutColumn4.getStyle().set("flex-grow", "1");
                icon.setIcon("lumo:user");
                icon.getStyle().set("width", "200px");
                icon.getStyle().set("height", "100px");
                layoutColumn5.setHeightFull();
                layoutRow.setFlexGrow(1.0, layoutColumn5);
                layoutColumn5.getStyle().set("width", "min-content");
                layoutColumn5.setMinWidth("200px");
                layoutColumn5.getStyle().set("flex-grow", "1");
                layoutColumn5.setJustifyContentMode(JustifyContentMode.CENTER);
                layoutColumn5.setAlignItems(Alignment.START);
                h1.setText("Relacionamiento Estratégico");
                h1.getStyle().set("width", "max-content");
                layoutColumn6.setHeightFull();
                layoutRow.setFlexGrow(1.0, layoutColumn6);
                layoutColumn6.getStyle().set("width", "min-content");
                layoutColumn6.setMinWidth("200px");
                layoutColumn6.getStyle().set("height", "100px");
                layoutColumn6.setJustifyContentMode(JustifyContentMode.CENTER);
                layoutColumn6.setAlignItems(Alignment.END);
                layoutRow3.addClassName(Gap.MEDIUM);
                layoutRow3.getStyle().set("width", "100%");
                layoutRow3.getStyle().set("flex-grow", "1");
                layoutColumn7.getStyle().set("flex-grow", "1");
                layoutColumn3.addClassName(Padding.XSMALL);
                layoutColumn3.getStyle().set("width", "100%");
                layoutColumn3.getStyle().set("flex-grow", "1");
                layoutRow4.addClassName(Gap.MEDIUM);
                layoutRow4.getStyle().set("width", "100%");
                layoutRow4.getStyle().set("height", "min-content");
                layoutRow4.setAlignItems(Alignment.START);
                layoutRow4.setJustifyContentMode(JustifyContentMode.START);
                buttonSecondary.setText("Inicio");
                layoutRow4.setAlignSelf(FlexComponent.Alignment.CENTER, buttonSecondary);
                buttonSecondary.getStyle().set("width", "min-content");
                textMedium.setText(
                                "La Universidad de La Salle avanza en la consolidación de sistemas de gestión académico-administrativos que permitan la optimización de los procesos, la atención oportuna y la representación institucional con entidades públicas y privadas, homólogas y organismos de cooperación en general.");
                layoutColumn3.setAlignSelf(FlexComponent.Alignment.CENTER, textMedium);
                textMedium.getStyle().set("width", "100%");
                textMedium.getStyle().set("font-size", "var(--lumo-font-size-m)");
                textMedium2.setText(
                                "En este sentido, la Oficina de Relaciones Internacionales e Interinstitucionales (ORII) presenta el esquema procedimental en línea para la solicitud de trámite y gestión de convenios el cual podrán utilizar no sólo para realizar el proceso administrativo de suscripción, sino también para realizar seguimiento al proceso interno y la ejecución de actividades en el marco de una nueva alianza estratégica.");
                layoutColumn3.setAlignSelf(FlexComponent.Alignment.CENTER, textMedium2);
                textMedium2.getStyle().set("width", "100%");
                textMedium2.getStyle().set("height", "52px");
                textMedium2.getStyle().set("font-size", "var(--lumo-font-size-m)");
                layoutColumn8.getStyle().set("flex-grow", "1");
                layoutRow5.addClassName(Gap.MEDIUM);
                layoutRow5.getStyle().set("width", "100%");
                layoutRow5.getStyle().set("height", "min-content");
                layoutColumn9.getStyle().set("flex-grow", "1");
                layoutRow8.addClassName(Gap.MEDIUM);
                layoutRow8.getStyle().set("width", "100%");
                layoutRow8.getStyle().set("height", "min-content");
                layoutColumn10.getStyle().set("flex-grow", "1");
                layoutRow6.addClassName(Gap.MEDIUM);
                layoutRow6.getStyle().set("width", "100%");
                layoutRow6.getStyle().set("height", "min-content");
                layoutColumn11.getStyle().set("flex-grow", "1");
                h6.setText(
                                "Contáctenos: Carrera 5ª No. 59A-44 | Tel: (571) 348 8000 Ext. 1107 | Bogotá, Colombia | relainter@lasalle.edu.co\r© Todos los derechos reservados. Contenido propiedad exclusiva de Universidad de La Salle.");
                layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, h6);
                h6.getStyle().set("width", "max-content");
                layoutColumn12.getStyle().set("flex-grow", "1");
                layoutRow9.addClassName(Gap.MEDIUM);
                layoutRow9.getStyle().set("width", "100%");
                layoutRow9.getStyle().set("height", "min-content");
                getContent().add(layoutColumn2);
                layoutColumn2.add(layoutRow7);
                layoutColumn2.add(layoutRow);
                layoutRow.add(layoutRow2);
                layoutRow2.add(layoutColumn4);
                layoutRow2.add(icon);
                layoutRow.add(layoutColumn5);
                layoutRow.add(h1);
                layoutRow.add(layoutColumn6);
                layoutColumn2.add(layoutRow3);
                layoutRow3.add(layoutColumn7);
                layoutRow3.add(layoutColumn3);
                layoutColumn3.add(layoutRow4);
                layoutRow4.add(buttonSecondary);
                layoutColumn3.add(textMedium);
                layoutColumn3.add(textMedium2);
                layoutRow3.add(layoutColumn8);
                layoutColumn2.add(layoutRow5);
                layoutRow5.add(layoutColumn9);
                layoutRow5.add(layoutRow8);
                layoutRow5.add(layoutColumn10);
                layoutColumn2.add(layoutRow6);
                layoutRow6.add(layoutColumn11);
                layoutRow6.add(h6);
                layoutRow6.add(layoutColumn12);
                layoutColumn2.add(layoutRow9);
        }
}
