package lasalle.edu.co.views.ingles_relacionamientoestratégico;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H6;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import com.vaadin.flow.theme.lumo.LumoUtility.Padding;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Ingles_Relacionamiento Estratégico")
@Route("my-view")
@Menu(order = 3, icon = LineAwesomeIconUrl.PENCIL_RULER_SOLID)
public class Ingles_RelacionamientoEstratégicoView extends Composite<VerticalLayout> {

        public Ingles_RelacionamientoEstratégicoView() {
                HorizontalLayout layoutRow7 = new HorizontalLayout();
                HorizontalLayout layoutRow = new HorizontalLayout();
                HorizontalLayout layoutRow2 = new HorizontalLayout();
                VerticalLayout layoutColumn3 = new VerticalLayout();
                Icon icon = new Icon();
                VerticalLayout layoutColumn4 = new VerticalLayout();
                H1 h1 = new H1();
                VerticalLayout layoutColumn5 = new VerticalLayout();
                HorizontalLayout layoutRow3 = new HorizontalLayout();
                VerticalLayout layoutColumn6 = new VerticalLayout();
                VerticalLayout layoutColumn2 = new VerticalLayout();
                HorizontalLayout layoutRow4 = new HorizontalLayout();
                Button buttonSecondary = new Button();
                Paragraph textMedium = new Paragraph();
                Paragraph textMedium2 = new Paragraph();
                VerticalLayout layoutColumn7 = new VerticalLayout();
                HorizontalLayout layoutRow5 = new HorizontalLayout();
                VerticalLayout layoutColumn8 = new VerticalLayout();
                HorizontalLayout layoutRow8 = new HorizontalLayout();
                VerticalLayout layoutColumn9 = new VerticalLayout();
                HorizontalLayout layoutRow6 = new HorizontalLayout();
                VerticalLayout layoutColumn10 = new VerticalLayout();
                H6 h6 = new H6();
                VerticalLayout layoutColumn11 = new VerticalLayout();
                HorizontalLayout layoutRow9 = new HorizontalLayout();
                getContent().getStyle().set("width", "100%");
                getContent().getStyle().set("flex-grow", "1");
                layoutRow7.addClassName(Gap.MEDIUM);
                layoutRow7.getStyle().set("width", "100%");
                layoutRow7.getStyle().set("height", "min-content");
                layoutRow.addClassName(Gap.MEDIUM);
                layoutRow.getStyle().set("width", "100%");
                layoutRow.getStyle().set("height", "min-content");
                layoutRow.setAlignItems(Alignment.CENTER);
                layoutRow.setJustifyContentMode(JustifyContentMode.CENTER);
                layoutRow2.addClassName(Gap.MEDIUM);
                layoutRow2.getStyle().set("width", "100%");
                layoutRow2.getStyle().set("height", "min-content");
                layoutColumn3.getStyle().set("flex-grow", "1");
                icon.setIcon("lumo:user");
                icon.getStyle().set("width", "200px");
                icon.getStyle().set("height", "100px");
                layoutColumn4.setHeightFull();
                layoutRow.setFlexGrow(1.0, layoutColumn4);
                layoutColumn4.getStyle().set("width", "min-content");
                layoutColumn4.setMinWidth("200px");
                layoutColumn4.getStyle().set("flex-grow", "1");
                layoutColumn4.setJustifyContentMode(JustifyContentMode.CENTER);
                layoutColumn4.setAlignItems(Alignment.START);
                h1.setText("Strategic Engagement");
                h1.getStyle().set("width", "max-content");
                layoutColumn5.setHeightFull();
                layoutRow.setFlexGrow(1.0, layoutColumn5);
                layoutColumn5.getStyle().set("width", "min-content");
                layoutColumn5.setMinWidth("200px");
                layoutColumn5.getStyle().set("height", "100px");
                layoutColumn5.setJustifyContentMode(JustifyContentMode.CENTER);
                layoutColumn5.setAlignItems(Alignment.END);
                layoutRow3.addClassName(Gap.MEDIUM);
                layoutRow3.getStyle().set("width", "100%");
                layoutRow3.getStyle().set("flex-grow", "1");
                layoutColumn6.getStyle().set("flex-grow", "1");
                layoutColumn2.addClassName(Padding.XSMALL);
                layoutColumn2.getStyle().set("width", "100%");
                layoutColumn2.getStyle().set("flex-grow", "1");
                layoutRow4.addClassName(Gap.MEDIUM);
                layoutRow4.getStyle().set("width", "100%");
                layoutRow4.getStyle().set("height", "min-content");
                layoutRow4.setAlignItems(Alignment.START);
                layoutRow4.setJustifyContentMode(JustifyContentMode.START);
                buttonSecondary.setText("Home");
                layoutRow4.setAlignSelf(FlexComponent.Alignment.CENTER, buttonSecondary);
                buttonSecondary.getStyle().set("width", "min-content");
                textMedium.setText(
                                "La Salle University is making progress in the consolidation of academic and administrative management systems that enable process optimization, timely service, and institutional representation before public and private entities, peer institutions, and cooperation organizations in general.");
                layoutColumn2.setAlignSelf(FlexComponent.Alignment.CENTER, textMedium);
                textMedium.getStyle().set("width", "100%");
                textMedium.getStyle().set("font-size", "var(--lumo-font-size-m)");
                textMedium2.setText(
                                "In this regard, the Office of International and Interinstitutional Relations (ORII) presents the online procedural framework for the request and management of agreements. This tool can be used not only to carry out the administrative subscription process, but also to monitor the internal workflow and the execution of activities within the framework of a new strategic partnership.");
                layoutColumn2.setAlignSelf(FlexComponent.Alignment.CENTER, textMedium2);
                textMedium2.getStyle().set("width", "100%");
                textMedium2.getStyle().set("height", "52px");
                textMedium2.getStyle().set("font-size", "var(--lumo-font-size-m)");
                layoutColumn7.getStyle().set("flex-grow", "1");
                layoutRow5.addClassName(Gap.MEDIUM);
                layoutRow5.getStyle().set("width", "100%");
                layoutRow5.getStyle().set("height", "min-content");
                layoutColumn8.getStyle().set("flex-grow", "1");
                layoutRow8.addClassName(Gap.MEDIUM);
                layoutRow8.getStyle().set("width", "100%");
                layoutRow8.getStyle().set("height", "min-content");
                layoutColumn9.getStyle().set("flex-grow", "1");
                layoutRow6.addClassName(Gap.MEDIUM);
                layoutRow6.getStyle().set("width", "100%");
                layoutRow6.getStyle().set("height", "min-content");
                layoutColumn10.getStyle().set("flex-grow", "1");
                h6.setText(
                                "Contact us: Carrera 5ª No. 59A-44 | Tel: (571) 348 8000 Ext. 1107 | Bogotá, Colombia | relainter@lasalle.edu.co © All rights reserved. Content is the exclusive property of Universidad de La Salle.");
                layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, h6);
                h6.getStyle().set("width", "max-content");
                layoutColumn11.getStyle().set("flex-grow", "1");
                layoutRow9.addClassName(Gap.MEDIUM);
                layoutRow9.getStyle().set("width", "100%");
                layoutRow9.getStyle().set("height", "min-content");
                getContent().add(layoutRow7);
                getContent().add(layoutRow);
                layoutRow.add(layoutRow2);
                layoutRow2.add(layoutColumn3);
                layoutRow2.add(icon);
                layoutRow.add(layoutColumn4);
                layoutRow.add(h1);
                layoutRow.add(layoutColumn5);
                getContent().add(layoutRow3);
                layoutRow3.add(layoutColumn6);
                layoutRow3.add(layoutColumn2);
                layoutColumn2.add(layoutRow4);
                layoutRow4.add(buttonSecondary);
                layoutColumn2.add(textMedium);
                layoutColumn2.add(textMedium2);
                layoutRow3.add(layoutColumn7);
                getContent().add(layoutRow5);
                layoutRow5.add(layoutColumn8);
                layoutRow5.add(layoutRow8);
                layoutRow5.add(layoutColumn9);
                getContent().add(layoutRow6);
                layoutRow6.add(layoutColumn10);
                layoutRow6.add(h6);
                layoutRow6.add(layoutColumn11);
                getContent().add(layoutRow9);
        }
}
