package lasalle.edu.co.views.ingles_verconvenios;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.combobox.MultiSelectComboBox;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H5;
import com.vaadin.flow.component.html.H6;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.spring.data.VaadinSpringDataHelpers;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import com.vaadin.flow.theme.lumo.LumoUtility.Padding;
import java.util.ArrayList;
import java.util.List;
import lasalle.edu.co.data.SamplePerson;
import lasalle.edu.co.services.SamplePersonService;
import org.springframework.beans.factory.annotation.Autowired;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Ingles_Ver Convenios")
@Route("my-view10")
@Menu(order = 5, icon = LineAwesomeIconUrl.PENCIL_RULER_SOLID)
@Uses(Icon.class)
public class Ingles_VerConveniosView extends Composite<VerticalLayout> {

    public Ingles_VerConveniosView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        HorizontalLayout layoutRow = new HorizontalLayout();
        HorizontalLayout layoutRow16 = new HorizontalLayout();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        VerticalLayout layoutColumn12 = new VerticalLayout();
        Icon icon = new Icon();
        H1 h1 = new H1();
        VerticalLayout layoutColumn13 = new VerticalLayout();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        VerticalLayout layoutColumn14 = new VerticalLayout();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        Button buttonSecondary = new Button();
        Button buttonTertiary = new Button();
        Button buttonTertiary2 = new Button();
        Button buttonTertiary3 = new Button();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        H5 h5 = new H5();
        HorizontalLayout layoutRow7 = new HorizontalLayout();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        MultiSelectComboBox multiSelectComboBox = new MultiSelectComboBox();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        MultiSelectComboBox multiSelectComboBox2 = new MultiSelectComboBox();
        HorizontalLayout layoutRow8 = new HorizontalLayout();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        MultiSelectComboBox multiSelectComboBox3 = new MultiSelectComboBox();
        VerticalLayout layoutColumn7 = new VerticalLayout();
        MultiSelectComboBox multiSelectComboBox4 = new MultiSelectComboBox();
        HorizontalLayout layoutRow9 = new HorizontalLayout();
        VerticalLayout layoutColumn8 = new VerticalLayout();
        MultiSelectComboBox multiSelectComboBox5 = new MultiSelectComboBox();
        VerticalLayout layoutColumn9 = new VerticalLayout();
        MultiSelectComboBox multiSelectComboBox6 = new MultiSelectComboBox();
        HorizontalLayout layoutRow10 = new HorizontalLayout();
        VerticalLayout layoutColumn10 = new VerticalLayout();
        Button buttonSecondary2 = new Button();
        VerticalLayout layoutColumn11 = new VerticalLayout();
        Button buttonSecondary3 = new Button();
        HorizontalLayout layoutRow11 = new HorizontalLayout();
        NumberField numberField = new NumberField();
        HorizontalLayout layoutRow12 = new HorizontalLayout();
        Grid basicGrid = new Grid(SamplePerson.class);
        VerticalLayout layoutColumn15 = new VerticalLayout();
        HorizontalLayout layoutRow13 = new HorizontalLayout();
        HorizontalLayout layoutRow14 = new HorizontalLayout();
        VerticalLayout layoutColumn16 = new VerticalLayout();
        HorizontalLayout layoutRow17 = new HorizontalLayout();
        VerticalLayout layoutColumn17 = new VerticalLayout();
        HorizontalLayout layoutRow15 = new HorizontalLayout();
        VerticalLayout layoutColumn18 = new VerticalLayout();
        H6 h6 = new H6();
        VerticalLayout layoutColumn19 = new VerticalLayout();
        HorizontalLayout layoutRow18 = new HorizontalLayout();
        getContent().setHeightFull();
        getContent().setWidthFull();
        layoutColumn2.getStyle().set("width", "100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.getStyle().set("width", "100%");
        layoutRow.getStyle().set("height", "min-content");
        layoutRow16.addClassName(Gap.MEDIUM);
        layoutRow16.getStyle().set("width", "100%");
        layoutRow16.getStyle().set("height", "min-content");
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.getStyle().set("width", "100%");
        layoutRow2.getStyle().set("height", "min-content");
        layoutRow2.setAlignItems(Alignment.CENTER);
        layoutRow2.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.getStyle().set("width", "100%");
        layoutRow3.getStyle().set("height", "min-content");
        layoutColumn12.getStyle().set("flex-grow", "1");
        icon.setIcon("lumo:user");
        icon.getStyle().set("width", "200px");
        icon.getStyle().set("height", "100px");
        h1.setText("Strategic Partnerships and Agreements");
        layoutRow2.setAlignSelf(FlexComponent.Alignment.CENTER, h1);
        h1.getStyle().set("width", "max-content");
        layoutColumn13.getStyle().set("flex-grow", "1");
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.getStyle().set("width", "100%");
        layoutRow4.getStyle().set("flex-grow", "1");
        layoutColumn14.getStyle().set("flex-grow", "1");
        layoutColumn3.addClassName(Padding.XSMALL);
        layoutColumn3.getStyle().set("width", "100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.getStyle().set("width", "100%");
        layoutRow5.getStyle().set("height", "min-content");
        buttonSecondary.setText("Home");
        layoutRow5.setAlignSelf(FlexComponent.Alignment.CENTER, buttonSecondary);
        buttonSecondary.getStyle().set("width", "min-content");
        buttonTertiary.setText("Submit a New Agreement");
        buttonTertiary.getStyle().set("width", "min-content");
        buttonTertiary.addThemeVariants(ButtonVariant.LUMO_TERTIARY);
        buttonTertiary2.setText("View My Agreements");
        buttonTertiary2.getStyle().set("width", "min-content");
        buttonTertiary2.addThemeVariants(ButtonVariant.LUMO_TERTIARY);
        buttonTertiary3.setText("Administrative Units Login");
        buttonTertiary3.getStyle().set("width", "min-content");
        buttonTertiary3.addThemeVariants(ButtonVariant.LUMO_TERTIARY);
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.getStyle().set("width", "100%");
        layoutRow6.getStyle().set("height", "min-content");
        h5.setText("Please select the search criteria:");
        h5.getStyle().set("width", "max-content");
        layoutRow7.addClassName(Gap.MEDIUM);
        layoutRow7.getStyle().set("width", "100%");
        layoutRow7.getStyle().set("height", "min-content");
        layoutRow7.setAlignItems(Alignment.CENTER);
        layoutRow7.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn4.getStyle().set("flex-grow", "1");
        multiSelectComboBox.setLabel("Country");
        multiSelectComboBox.getStyle().set("width", "min-content");
        setMultiSelectComboBoxSampleData(multiSelectComboBox);
        layoutColumn5.getStyle().set("flex-grow", "1");
        multiSelectComboBox2.setLabel("Faculties and Departments");
        multiSelectComboBox2.getStyle().set("width", "min-content");
        setMultiSelectComboBoxSampleData(multiSelectComboBox2);
        layoutRow8.addClassName(Gap.MEDIUM);
        layoutRow8.getStyle().set("width", "100%");
        layoutRow8.getStyle().set("height", "min-content");
        layoutRow8.setAlignItems(Alignment.CENTER);
        layoutRow8.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn6.getStyle().set("flex-grow", "1");
        multiSelectComboBox3.setLabel("Type of Agreement");
        multiSelectComboBox3.getStyle().set("width", "min-content");
        setMultiSelectComboBoxSampleData(multiSelectComboBox3);
        layoutColumn7.getStyle().set("flex-grow", "1");
        multiSelectComboBox4.setLabel("Programs");
        multiSelectComboBox4.getStyle().set("width", "min-content");
        setMultiSelectComboBoxSampleData(multiSelectComboBox4);
        layoutRow9.addClassName(Gap.MEDIUM);
        layoutRow9.getStyle().set("width", "100%");
        layoutRow9.getStyle().set("height", "min-content");
        layoutRow9.setAlignItems(Alignment.CENTER);
        layoutRow9.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn8.getStyle().set("flex-grow", "1");
        multiSelectComboBox5.setLabel("Agreement Modality");
        multiSelectComboBox5.getStyle().set("width", "min-content");
        setMultiSelectComboBoxSampleData(multiSelectComboBox5);
        layoutColumn9.getStyle().set("flex-grow", "1");
        multiSelectComboBox6.setLabel("Status");
        multiSelectComboBox6.getStyle().set("width", "min-content");
        setMultiSelectComboBoxSampleData(multiSelectComboBox6);
        layoutRow10.addClassName(Gap.MEDIUM);
        layoutRow10.getStyle().set("width", "100%");
        layoutRow10.getStyle().set("height", "min-content");
        layoutRow10.setAlignItems(Alignment.CENTER);
        layoutRow10.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutColumn10.getStyle().set("flex-grow", "1");
        buttonSecondary2.setText("Reset");
        buttonSecondary2.getStyle().set("width", "min-content");
        layoutColumn11.getStyle().set("flex-grow", "1");
        buttonSecondary3.setText("Search");
        buttonSecondary3.getStyle().set("width", "min-content");
        layoutRow11.addClassName(Gap.MEDIUM);
        layoutRow11.getStyle().set("width", "100%");
        layoutRow11.getStyle().set("height", "min-content");
        layoutRow11.setAlignItems(Alignment.START);
        layoutRow11.setJustifyContentMode(JustifyContentMode.END);
        numberField.setLabel("Agreements Found");
        numberField.getStyle().set("width", "min-content");
        layoutRow12.addClassName(Gap.MEDIUM);
        layoutRow12.getStyle().set("width", "100%");
        layoutRow12.getStyle().set("height", "min-content");
        basicGrid.getStyle().set("width", "100%");
        basicGrid.getStyle().set("flex-grow", "0");
        setGridSampleData(basicGrid);
        layoutColumn15.getStyle().set("flex-grow", "1");
        layoutRow13.addClassName(Gap.MEDIUM);
        layoutRow13.getStyle().set("width", "100%");
        layoutRow13.getStyle().set("height", "min-content");
        layoutRow14.addClassName(Gap.MEDIUM);
        layoutRow14.getStyle().set("width", "100%");
        layoutRow14.getStyle().set("height", "min-content");
        layoutColumn16.getStyle().set("flex-grow", "1");
        layoutRow17.addClassName(Gap.MEDIUM);
        layoutRow17.getStyle().set("width", "100%");
        layoutRow17.getStyle().set("height", "min-content");
        layoutColumn17.getStyle().set("flex-grow", "1");
        layoutRow15.addClassName(Gap.MEDIUM);
        layoutRow15.getStyle().set("width", "100%");
        layoutRow15.getStyle().set("height", "min-content");
        layoutColumn18.getStyle().set("flex-grow", "1");
        h6.setText(
                "Contact us: Carrera 5ª No. 59A-44 | Tel: (571) 348 8000 Ext. 1107 | Bogotá, Colombia | relainter@lasalle.edu.co © All rights reserved. Content is the exclusive property of Universidad de La Salle.");
        layoutRow15.setAlignSelf(FlexComponent.Alignment.CENTER, h6);
        h6.getStyle().set("width", "max-content");
        layoutColumn19.getStyle().set("flex-grow", "1");
        layoutRow18.addClassName(Gap.MEDIUM);
        layoutRow18.getStyle().set("width", "100%");
        layoutRow18.getStyle().set("height", "min-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(layoutRow);
        layoutRow.add(layoutRow16);
        layoutColumn2.add(layoutRow2);
        layoutRow2.add(layoutRow3);
        layoutRow3.add(layoutColumn12);
        layoutRow3.add(icon);
        layoutRow2.add(h1);
        layoutRow2.add(layoutColumn13);
        layoutColumn2.add(layoutRow4);
        layoutRow4.add(layoutColumn14);
        layoutRow4.add(layoutColumn3);
        layoutColumn3.add(layoutRow5);
        layoutRow5.add(buttonSecondary);
        layoutRow5.add(buttonTertiary);
        layoutRow5.add(buttonTertiary2);
        layoutRow5.add(buttonTertiary3);
        layoutColumn3.add(layoutRow6);
        layoutRow6.add(h5);
        layoutColumn3.add(layoutRow7);
        layoutRow7.add(layoutColumn4);
        layoutColumn4.add(multiSelectComboBox);
        layoutRow7.add(layoutColumn5);
        layoutColumn5.add(multiSelectComboBox2);
        layoutColumn3.add(layoutRow8);
        layoutRow8.add(layoutColumn6);
        layoutColumn6.add(multiSelectComboBox3);
        layoutRow8.add(layoutColumn7);
        layoutColumn7.add(multiSelectComboBox4);
        layoutColumn3.add(layoutRow9);
        layoutRow9.add(layoutColumn8);
        layoutColumn8.add(multiSelectComboBox5);
        layoutRow9.add(layoutColumn9);
        layoutColumn9.add(multiSelectComboBox6);
        layoutColumn3.add(layoutRow10);
        layoutRow10.add(layoutColumn10);
        layoutColumn10.add(buttonSecondary2);
        layoutRow10.add(layoutColumn11);
        layoutColumn11.add(buttonSecondary3);
        layoutColumn3.add(layoutRow11);
        layoutRow11.add(numberField);
        layoutColumn3.add(layoutRow12);
        layoutRow12.add(basicGrid);
        layoutRow4.add(layoutColumn15);
        layoutColumn2.add(layoutRow13);
        layoutRow13.add(layoutRow14);
        layoutRow14.add(layoutColumn16);
        layoutRow14.add(layoutRow17);
        layoutRow14.add(layoutColumn17);
        layoutColumn2.add(layoutRow15);
        layoutRow15.add(layoutColumn18);
        layoutRow15.add(h6);
        layoutRow15.add(layoutColumn19);
        layoutColumn2.add(layoutRow18);
    }

    record SampleItem(String value, String label, Boolean disabled) {
    }

    private void setMultiSelectComboBoxSampleData(MultiSelectComboBox multiSelectComboBox) {
        List<SampleItem> sampleItems = new ArrayList<>();
        sampleItems.add(new SampleItem("first", "First", null));
        sampleItems.add(new SampleItem("second", "Second", null));
        sampleItems.add(new SampleItem("third", "Third", Boolean.TRUE));
        sampleItems.add(new SampleItem("fourth", "Fourth", null));
        multiSelectComboBox.setItems(sampleItems);
        multiSelectComboBox.setItemLabelGenerator(item -> ((SampleItem) item).label());
    }

    private void setGridSampleData(Grid grid) {
        grid.setItems(query -> samplePersonService.list(VaadinSpringDataHelpers.toSpringPageRequest(query)).stream());
    }

    @Autowired()
    private SamplePersonService samplePersonService;
}
