package lasalle.edu.co.views.ingresotramitarunnuevoconvenio;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H6;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.login.LoginForm;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Ingreso Tramitar un Nuevo Convenio")
@Route("my-view3")
@Menu(order = 6, icon = LineAwesomeIconUrl.PENCIL_RULER_SOLID)
public class IngresoTramitarunNuevoConvenioView extends Composite<VerticalLayout> {

    public IngresoTramitarunNuevoConvenioView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        HorizontalLayout layoutRow8 = new HorizontalLayout();
        HorizontalLayout layoutRow = new HorizontalLayout();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        Icon icon = new Icon();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        H1 h1 = new H1();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        VerticalLayout layoutColumn7 = new VerticalLayout();
        VerticalLayout layoutColumn8 = new VerticalLayout();
        VerticalLayout layoutColumn9 = new VerticalLayout();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        VerticalLayout layoutColumn10 = new VerticalLayout();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        VerticalLayout layoutColumn11 = new VerticalLayout();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        Button buttonSecondary = new Button();
        HorizontalLayout layoutRow9 = new HorizontalLayout();
        H2 h2 = new H2();
        HorizontalLayout layoutRow10 = new HorizontalLayout();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        LoginForm loginForm = new LoginForm();
        VerticalLayout layoutColumn12 = new VerticalLayout();
        HorizontalLayout layoutRow11 = new HorizontalLayout();
        HorizontalLayout layoutRow7 = new HorizontalLayout();
        VerticalLayout layoutColumn13 = new VerticalLayout();
        H6 h6 = new H6();
        VerticalLayout layoutColumn14 = new VerticalLayout();
        HorizontalLayout layoutRow12 = new HorizontalLayout();
        getContent().getStyle().set("width", "100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutColumn2.getStyle().set("width", "100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        layoutRow8.addClassName(Gap.MEDIUM);
        layoutRow8.getStyle().set("width", "100%");
        layoutRow8.getStyle().set("height", "min-content");
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.getStyle().set("width", "100%");
        layoutRow.getStyle().set("height", "min-content");
        layoutRow.setAlignItems(Alignment.CENTER);
        layoutRow.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.getStyle().set("width", "100%");
        layoutRow2.getStyle().set("height", "min-content");
        layoutColumn5.getStyle().set("flex-grow", "1");
        icon.setIcon("lumo:user");
        icon.getStyle().set("width", "200px");
        icon.getStyle().set("height", "100px");
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.getStyle().set("width", "100%");
        layoutRow3.getStyle().set("height", "min-content");
        layoutRow3.setAlignItems(Alignment.CENTER);
        layoutRow3.setJustifyContentMode(JustifyContentMode.CENTER);
        h1.setText("Tramitar un Nuevo Convenio");
        layoutRow3.setAlignSelf(FlexComponent.Alignment.CENTER, h1);
        h1.getStyle().set("width", "max-content");
        layoutColumn6.getStyle().set("flex-grow", "1");
        layoutColumn7.getStyle().set("flex-grow", "1");
        layoutColumn8.getStyle().set("flex-grow", "1");
        layoutColumn9.getStyle().set("flex-grow", "1");
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.getStyle().set("width", "100%");
        layoutRow4.getStyle().set("height", "min-content");
        layoutColumn10.getStyle().set("flex-grow", "1");
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.getStyle().set("width", "100%");
        layoutRow5.getStyle().set("flex-grow", "1");
        layoutColumn11.getStyle().set("flex-grow", "1");
        layoutColumn3.getStyle().set("flex-grow", "1");
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.getStyle().set("width", "100%");
        layoutRow6.getStyle().set("height", "min-content");
        buttonSecondary.setText("Inicio");
        layoutRow6.setAlignSelf(FlexComponent.Alignment.CENTER, buttonSecondary);
        buttonSecondary.getStyle().set("width", "min-content");
        layoutRow9.addClassName(Gap.MEDIUM);
        layoutRow9.getStyle().set("width", "100%");
        layoutRow9.getStyle().set("height", "min-content");
        h2.setText("Ingreso Usuarios Lasallistas");
        h2.getStyle().set("width", "max-content");
        layoutRow10.addClassName(Gap.MEDIUM);
        layoutRow10.getStyle().set("width", "100%");
        layoutRow10.getStyle().set("height", "min-content");
        layoutColumn4.getStyle().set("width", "100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        loginForm.getStyle().set("width", "100%");
        layoutColumn12.getStyle().set("flex-grow", "1");
        layoutRow11.addClassName(Gap.MEDIUM);
        layoutRow11.getStyle().set("width", "100%");
        layoutRow11.getStyle().set("height", "min-content");
        layoutRow7.addClassName(Gap.MEDIUM);
        layoutRow7.getStyle().set("width", "100%");
        layoutRow7.getStyle().set("height", "min-content");
        layoutColumn13.getStyle().set("flex-grow", "1");
        h6.setText(
                "Contáctenos: Carrera 5ª No. 59A-44 | Tel: (571) 348 8000 Ext. 1107 | Bogotá, Colombia | relainter@lasalle.edu.co\r\n© Todos los derechos reservados. Contenido propiedad exclusiva de Universidad de La Salle.");
        layoutRow7.setAlignSelf(FlexComponent.Alignment.CENTER, h6);
        h6.getStyle().set("width", "max-content");
        layoutColumn14.getStyle().set("flex-grow", "1");
        layoutRow12.addClassName(Gap.MEDIUM);
        layoutRow12.getStyle().set("width", "100%");
        layoutRow12.getStyle().set("height", "min-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(layoutRow8);
        layoutColumn2.add(layoutRow);
        layoutRow.add(layoutRow2);
        layoutRow2.add(layoutColumn5);
        layoutRow2.add(icon);
        layoutRow2.add(layoutRow3);
        layoutRow3.add(h1);
        layoutRow3.add(layoutColumn6);
        layoutRow3.add(layoutColumn7);
        layoutRow3.add(layoutColumn8);
        layoutRow3.add(layoutColumn9);
        layoutColumn2.add(layoutRow4);
        layoutRow4.add(layoutColumn10);
        layoutColumn2.add(layoutRow5);
        layoutRow5.add(layoutColumn11);
        layoutRow5.add(layoutColumn3);
        layoutColumn3.add(layoutRow6);
        layoutRow6.add(buttonSecondary);
        layoutColumn3.add(layoutRow9);
        layoutColumn3.add(h2);
        layoutColumn3.add(layoutRow10);
        layoutRow5.add(layoutColumn4);
        layoutColumn4.add(loginForm);
        layoutRow5.add(layoutColumn12);
        layoutColumn2.add(layoutRow11);
        layoutColumn2.add(layoutRow7);
        layoutRow7.add(layoutColumn13);
        layoutRow7.add(h6);
        layoutRow7.add(layoutColumn14);
        layoutColumn2.add(layoutRow12);
    }
}
