package lasalle.edu.co.views.ingles_formulariotramitarunnuevoconvenio2;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.avatar.Avatar;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H4;
import com.vaadin.flow.component.html.H5;
import com.vaadin.flow.component.html.H6;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.select.Select;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import java.util.ArrayList;
import java.util.List;
import org.vaadin.lineawesome.LineAwesomeIconUrl;

@PageTitle("Ingles_ Formulario Tramitar un Nuevo Convenio2")
@Route("my-view12")
@Menu(order = 9, icon = LineAwesomeIconUrl.PENCIL_RULER_SOLID)
public class Ingles_FormularioTramitarunNuevoConvenio2View extends Composite<VerticalLayout> {

    public Ingles_FormularioTramitarunNuevoConvenio2View() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        HorizontalLayout layoutRow24 = new HorizontalLayout();
        HorizontalLayout layoutRow = new HorizontalLayout();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        VerticalLayout layoutColumn5 = new VerticalLayout();
        Icon icon = new Icon();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        H1 h1 = new H1();
        VerticalLayout layoutColumn6 = new VerticalLayout();
        VerticalLayout layoutColumn7 = new VerticalLayout();
        VerticalLayout layoutColumn8 = new VerticalLayout();
        VerticalLayout layoutColumn9 = new VerticalLayout();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        VerticalLayout layoutColumn10 = new VerticalLayout();
        Avatar avatar = new Avatar();
        Button buttonSecondary = new Button();
        Button buttonSecondary2 = new Button();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        VerticalLayout layoutColumn11 = new VerticalLayout();
        HorizontalLayout layoutRow6 = new HorizontalLayout();
        H5 h5 = new H5();
        VerticalLayout layoutColumn12 = new VerticalLayout();
        HorizontalLayout layoutRow7 = new HorizontalLayout();
        VerticalLayout layoutColumn13 = new VerticalLayout();
        HorizontalLayout layoutRow8 = new HorizontalLayout();
        H5 h52 = new H5();
        Select select = new Select();
        VerticalLayout layoutColumn14 = new VerticalLayout();
        HorizontalLayout layoutRow9 = new HorizontalLayout();
        VerticalLayout layoutColumn15 = new VerticalLayout();
        HorizontalLayout layoutRow10 = new HorizontalLayout();
        H4 h4 = new H4();
        VerticalLayout layoutColumn16 = new VerticalLayout();
        HorizontalLayout layoutRow11 = new HorizontalLayout();
        VerticalLayout layoutColumn17 = new VerticalLayout();
        HorizontalLayout layoutRow12 = new HorizontalLayout();
        H4 h42 = new H4();
        VerticalLayout layoutColumn18 = new VerticalLayout();
        HorizontalLayout layoutRow13 = new HorizontalLayout();
        VerticalLayout layoutColumn19 = new VerticalLayout();
        HorizontalLayout layoutRow14 = new HorizontalLayout();
        H4 h43 = new H4();
        VerticalLayout layoutColumn20 = new VerticalLayout();
        HorizontalLayout layoutRow15 = new HorizontalLayout();
        VerticalLayout layoutColumn21 = new VerticalLayout();
        HorizontalLayout layoutRow16 = new HorizontalLayout();
        H4 h44 = new H4();
        VerticalLayout layoutColumn22 = new VerticalLayout();
        HorizontalLayout layoutRow17 = new HorizontalLayout();
        VerticalLayout layoutColumn23 = new VerticalLayout();
        HorizontalLayout layoutRow18 = new HorizontalLayout();
        H4 h45 = new H4();
        VerticalLayout layoutColumn24 = new VerticalLayout();
        HorizontalLayout layoutRow19 = new HorizontalLayout();
        VerticalLayout layoutColumn25 = new VerticalLayout();
        HorizontalLayout layoutRow20 = new HorizontalLayout();
        H4 h46 = new H4();
        VerticalLayout layoutColumn26 = new VerticalLayout();
        HorizontalLayout layoutRow21 = new HorizontalLayout();
        VerticalLayout layoutColumn27 = new VerticalLayout();
        HorizontalLayout layoutRow22 = new HorizontalLayout();
        H4 h47 = new H4();
        VerticalLayout layoutColumn28 = new VerticalLayout();
        HorizontalLayout layoutRow23 = new HorizontalLayout();
        VerticalLayout layoutColumn29 = new VerticalLayout();
        H6 h6 = new H6();
        VerticalLayout layoutColumn30 = new VerticalLayout();
        HorizontalLayout layoutRow25 = new HorizontalLayout();
        getContent().setHeightFull();
        getContent().setWidthFull();
        layoutColumn2.getStyle().set("width", "100%");
        layoutColumn2.getStyle().set("flex-grow", "1");
        layoutColumn3.getStyle().set("width", "100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        layoutColumn4.getStyle().set("width", "100%");
        layoutColumn4.getStyle().set("flex-grow", "1");
        layoutRow24.addClassName(Gap.MEDIUM);
        layoutRow24.getStyle().set("width", "100%");
        layoutRow24.getStyle().set("height", "min-content");
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.getStyle().set("width", "100%");
        layoutRow.getStyle().set("height", "min-content");
        layoutRow.setAlignItems(Alignment.CENTER);
        layoutRow.setJustifyContentMode(JustifyContentMode.CENTER);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.getStyle().set("width", "100%");
        layoutRow2.getStyle().set("height", "min-content");
        layoutColumn5.getStyle().set("flex-grow", "1");
        icon.setIcon("lumo:user");
        icon.getStyle().set("width", "200px");
        icon.getStyle().set("height", "100px");
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.getStyle().set("width", "100%");
        layoutRow3.getStyle().set("height", "min-content");
        layoutRow3.setAlignItems(Alignment.CENTER);
        layoutRow3.setJustifyContentMode(JustifyContentMode.CENTER);
        h1.setText("Submit a New Agreement");
        layoutRow3.setAlignSelf(FlexComponent.Alignment.CENTER, h1);
        h1.getStyle().set("width", "max-content");
        layoutColumn6.getStyle().set("flex-grow", "1");
        layoutColumn7.getStyle().set("flex-grow", "1");
        layoutColumn8.getStyle().set("flex-grow", "1");
        layoutColumn9.getStyle().set("flex-grow", "1");
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.getStyle().set("width", "100%");
        layoutRow4.getStyle().set("height", "min-content");
        layoutColumn10.getStyle().set("flex-grow", "1");
        avatar.setName("Firstname Lastname");
        buttonSecondary.setText("Log Out");
        buttonSecondary.getStyle().set("width", "min-content");
        buttonSecondary2.setText("View My Agreements");
        buttonSecondary2.getStyle().set("width", "min-content");
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.getStyle().set("width", "100%");
        layoutRow5.getStyle().set("height", "min-content");
        layoutColumn11.getStyle().set("flex-grow", "1");
        layoutRow6.addClassName(Gap.MEDIUM);
        layoutRow6.getStyle().set("width", "100%");
        layoutRow6.getStyle().set("height", "min-content");
        h5.setText("Agreement Request Form");
        h5.getStyle().set("width", "max-content");
        layoutColumn12.getStyle().set("flex-grow", "1");
        layoutRow7.addClassName(Gap.MEDIUM);
        layoutRow7.getStyle().set("width", "100%");
        layoutRow7.getStyle().set("height", "min-content");
        layoutColumn13.getStyle().set("flex-grow", "1");
        layoutRow8.addClassName(Gap.MEDIUM);
        layoutRow8.getStyle().set("width", "100%");
        layoutRow8.getStyle().set("height", "min-content");
        h52.setText("Requested By *");
        h52.getStyle().set("width", "max-content");
        select.setLabel("Select");
        select.getStyle().set("width", "min-content");
        setSelectSampleData(select);
        layoutColumn14.getStyle().set("flex-grow", "1");
        layoutRow9.addClassName(Gap.MEDIUM);
        layoutRow9.getStyle().set("width", "100%");
        layoutRow9.getStyle().set("height", "min-content");
        layoutColumn15.getStyle().set("flex-grow", "1");
        layoutRow10.addClassName(Gap.MEDIUM);
        layoutRow10.getStyle().set("width", "100%");
        layoutRow10.getStyle().set("height", "min-content");
        h4.setText("Agreement Details");
        h4.getStyle().set("width", "max-content");
        layoutColumn16.getStyle().set("flex-grow", "1");
        layoutRow11.addClassName(Gap.MEDIUM);
        layoutRow11.getStyle().set("width", "100%");
        layoutRow11.getStyle().set("height", "min-content");
        layoutColumn17.getStyle().set("flex-grow", "1");
        layoutRow12.addClassName(Gap.MEDIUM);
        layoutRow12.getStyle().set("width", "100%");
        layoutRow12.getStyle().set("height", "min-content");
        h42.setText("2");
        h42.getStyle().set("width", "max-content");
        layoutColumn18.getStyle().set("flex-grow", "1");
        layoutRow13.addClassName(Gap.MEDIUM);
        layoutRow13.getStyle().set("width", "100%");
        layoutRow13.getStyle().set("height", "min-content");
        layoutColumn19.getStyle().set("flex-grow", "1");
        layoutRow14.addClassName(Gap.MEDIUM);
        layoutRow14.getStyle().set("width", "100%");
        layoutRow14.getStyle().set("height", "min-content");
        h43.setText("3");
        h43.getStyle().set("width", "max-content");
        layoutColumn20.getStyle().set("flex-grow", "1");
        layoutRow15.addClassName(Gap.MEDIUM);
        layoutRow15.getStyle().set("width", "100%");
        layoutRow15.getStyle().set("height", "min-content");
        layoutColumn21.getStyle().set("flex-grow", "1");
        layoutRow16.addClassName(Gap.MEDIUM);
        layoutRow16.getStyle().set("width", "100%");
        layoutRow16.getStyle().set("height", "min-content");
        h44.setText("4");
        h44.getStyle().set("width", "max-content");
        layoutColumn22.getStyle().set("flex-grow", "1");
        layoutRow17.addClassName(Gap.MEDIUM);
        layoutRow17.getStyle().set("width", "100%");
        layoutRow17.getStyle().set("height", "min-content");
        layoutColumn23.getStyle().set("flex-grow", "1");
        layoutRow18.addClassName(Gap.MEDIUM);
        layoutRow18.getStyle().set("width", "100%");
        layoutRow18.getStyle().set("height", "min-content");
        h45.setText("5");
        h45.getStyle().set("width", "max-content");
        layoutColumn24.getStyle().set("flex-grow", "1");
        layoutRow19.addClassName(Gap.MEDIUM);
        layoutRow19.getStyle().set("width", "100%");
        layoutRow19.getStyle().set("height", "min-content");
        layoutColumn25.getStyle().set("flex-grow", "1");
        layoutRow20.addClassName(Gap.MEDIUM);
        layoutRow20.getStyle().set("width", "100%");
        layoutRow20.getStyle().set("height", "min-content");
        h46.setText("6");
        h46.getStyle().set("width", "max-content");
        layoutColumn26.getStyle().set("flex-grow", "1");
        layoutRow21.addClassName(Gap.MEDIUM);
        layoutRow21.getStyle().set("width", "100%");
        layoutRow21.getStyle().set("height", "min-content");
        layoutColumn27.getStyle().set("flex-grow", "1");
        layoutRow22.addClassName(Gap.MEDIUM);
        layoutRow22.getStyle().set("width", "100%");
        layoutRow22.getStyle().set("height", "min-content");
        h47.setText("7");
        h47.getStyle().set("width", "max-content");
        layoutColumn28.getStyle().set("flex-grow", "1");
        layoutRow23.addClassName(Gap.MEDIUM);
        layoutRow23.getStyle().set("width", "100%");
        layoutRow23.getStyle().set("height", "min-content");
        layoutColumn29.getStyle().set("flex-grow", "1");
        h6.setText(
                "Contact us: Carrera 5ª No. 59A-44 | Tel: (571) 348 8000 Ext. 1107 | Bogotá, Colombia | relainter@lasalle.edu.co © All rights reserved. Content is the exclusive property of Universidad de La Salle.");
        layoutRow23.setAlignSelf(FlexComponent.Alignment.CENTER, h6);
        h6.getStyle().set("width", "max-content");
        layoutColumn30.getStyle().set("flex-grow", "1");
        layoutRow25.addClassName(Gap.MEDIUM);
        layoutRow25.getStyle().set("width", "100%");
        layoutRow25.getStyle().set("height", "min-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(layoutColumn3);
        layoutColumn3.add(layoutColumn4);
        layoutColumn4.add(layoutRow24);
        layoutColumn4.add(layoutRow);
        layoutRow.add(layoutRow2);
        layoutRow2.add(layoutColumn5);
        layoutRow2.add(icon);
        layoutRow2.add(layoutRow3);
        layoutRow3.add(h1);
        layoutRow3.add(layoutColumn6);
        layoutRow3.add(layoutColumn7);
        layoutRow3.add(layoutColumn8);
        layoutRow3.add(layoutColumn9);
        layoutColumn4.add(layoutRow4);
        layoutRow4.add(layoutColumn10);
        layoutRow4.add(avatar);
        layoutRow4.add(buttonSecondary);
        layoutRow4.add(buttonSecondary2);
        layoutColumn4.add(layoutRow5);
        layoutRow5.add(layoutColumn11);
        layoutRow5.add(layoutRow6);
        layoutRow6.add(h5);
        layoutRow5.add(layoutColumn12);
        layoutColumn4.add(layoutRow7);
        layoutRow7.add(layoutColumn13);
        layoutRow7.add(layoutRow8);
        layoutRow8.add(h52);
        layoutRow8.add(select);
        layoutRow7.add(layoutColumn14);
        layoutColumn4.add(layoutRow9);
        layoutRow9.add(layoutColumn15);
        layoutRow9.add(layoutRow10);
        layoutRow10.add(h4);
        layoutRow9.add(layoutColumn16);
        layoutColumn4.add(layoutRow11);
        layoutRow11.add(layoutColumn17);
        layoutRow11.add(layoutRow12);
        layoutRow12.add(h42);
        layoutRow11.add(layoutColumn18);
        layoutColumn4.add(layoutRow13);
        layoutRow13.add(layoutColumn19);
        layoutRow13.add(layoutRow14);
        layoutRow14.add(h43);
        layoutRow13.add(layoutColumn20);
        layoutColumn4.add(layoutRow15);
        layoutRow15.add(layoutColumn21);
        layoutRow15.add(layoutRow16);
        layoutRow16.add(h44);
        layoutRow15.add(layoutColumn22);
        layoutColumn4.add(layoutRow17);
        layoutRow17.add(layoutColumn23);
        layoutRow17.add(layoutRow18);
        layoutRow18.add(h45);
        layoutRow17.add(layoutColumn24);
        layoutColumn4.add(layoutRow19);
        layoutRow19.add(layoutColumn25);
        layoutRow19.add(layoutRow20);
        layoutRow20.add(h46);
        layoutRow19.add(layoutColumn26);
        layoutColumn4.add(layoutRow21);
        layoutRow21.add(layoutColumn27);
        layoutRow21.add(layoutRow22);
        layoutRow22.add(h47);
        layoutRow21.add(layoutColumn28);
        layoutColumn4.add(layoutRow23);
        layoutRow23.add(layoutColumn29);
        layoutRow23.add(h6);
        layoutRow23.add(layoutColumn30);
        layoutColumn4.add(layoutRow25);
    }

    record SampleItem(String value, String label, Boolean disabled) {
    }

    private void setSelectSampleData(Select select) {
        List<SampleItem> sampleItems = new ArrayList<>();
        sampleItems.add(new SampleItem("first", "First", null));
        sampleItems.add(new SampleItem("second", "Second", null));
        sampleItems.add(new SampleItem("third", "Third", Boolean.TRUE));
        sampleItems.add(new SampleItem("fourth", "Fourth", null));
        select.setItems(sampleItems);
        select.setItemLabelGenerator(item -> ((SampleItem) item).label());
        select.setItemEnabledProvider(item -> !Boolean.TRUE.equals(((SampleItem) item).disabled()));
    }
}
